### ISSUE TITLE
Electrum for FairCoin 2.3.3 won't connect

### ISSUE THREAD

**Issue by samu16** [FairCoinTeam/electrum-fair#7]
Hello,

My Electrum FairCoin Wallet (2.3.3) won't connect anymore.
Last time I ran it (about a month ago), there was no problem at all.
Yesterday, I wanted to send some coins and it just always shows 'Not connected'.
Auto connect is checked, my default servers are 'chain.fair.org' and 'fairelectrum.fair.coin.org', port 51002.
SSL is checked. No Proxy.

Please, can someone suggest what the problem is?
Thank you,
samu

**Comment by thokon00** [comment]
This is the old tree of the FairCoin1 wallet, which is deprecated since 18th of July. Please check https://download.faircoin.world/ for new Electrum packages. They are made available in one or two days. Alternatively you can checkout the release branch of the new tree here: https://github.com/faircoin/electrumfair/tree/2.7.18-fc

**Comment by samu16** [comment]
Thank You!
